# Generated by Django 3.2 on 2022-11-24 09:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221121_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerwaybill',
            old_name='contact_number',
            new_name='additonal_services',
        ),
        migrations.RenameField(
            model_name='customerwaybill',
            old_name='delivery_instruction',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='customerwaybill',
            old_name='refrenceno',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_point',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='CODAmount',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='billing_type',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='booking_no',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='cust_national_id',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='declare_value',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='destination_city',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='height',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='length',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='origin_city',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='pickup_point',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='pod_type',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='shiping_instruction',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='vol_weight',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='waybillno',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='customerwaybill',
            name='width',
        ),
        migrations.AddField(
            model_name='booking',
            name='request_for_schedule_pickup',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='Latest_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='booking_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_booking_id', to='core.booking'),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Courier-Informed', 'Courier-Informed'), ('Cancel-Booking', 'Cancel-Booking'), ('Scheduled', 'Scheduled'), ('Picked-Up', 'Picked-Up'), ('Miss-PickUp', 'Miss-PickUp'), ('Acknowledge', 'Acknowledge')], default='Booked', max_length=25, null=True, verbose_name='Booking Status'),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='bookingref',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Booking#'),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='chargable_weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_comapny_name', to='core.companyprofile'),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='customs_value',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='goods_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_goods_origin_city', to='core.city'),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='gross_weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='is_Email',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='is_Push',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='is_SMS',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='is_fav',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Account', 'Shipper-Account'), ('COD', 'Cash-On-Delivery')], default='Cash', max_length=50, null=True, verbose_name='Payment method'),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='ready_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='request_for_schedule_pickup',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Latest_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='chargable_weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_comapny_name', to='core.companyprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customs_value',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='goods_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_origin_city', to='core.city'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gross_weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Account', 'Shipper-Account'), ('COD', 'Cash-On-Delivery')], default='Cash', max_length=50, null=True, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pickup Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Pickup Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='piece_count',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ready_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerwaybill',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_consignee_booking', to='core.consignee'),
        ),
        migrations.AlterField(
            model_name='customerwaybill',
            name='pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pickup Date'),
        ),
        migrations.AlterField(
            model_name='customerwaybill',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Pickup Time'),
        ),
        migrations.AlterField(
            model_name='customerwaybill',
            name='piece_count',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='customerwaybill',
            name='shipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_shipment_type', to='core.standardcode'),
        ),
        migrations.AlterField(
            model_name='customerwaybill',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_shipper_booking', to='core.shipper'),
        ),
    ]
