# Generated by Django 3.2 on 2022-11-24 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221124_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerwaybill',
            name='booking_id',
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='booking_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_booking_no', to='core.booking'),
        ),
    ]
