# Generated by Django 3.2 on 2022-11-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221124_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='save_to_addressbook',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customerwaybill',
            name='save_to_addressbook',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
