# Generated by Django 3.2 on 2022-11-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221124_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='shipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_shipment_type', to='core.shipmenttype'),
        ),
        migrations.AlterField(
            model_name='customerwaybill',
            name='shipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_shipment_type', to='core.shipmenttype'),
        ),
    ]
