# Generated by Django 3.2 on 2022-11-27 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221124_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='goods_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_goods_origin_city', to='core.city'),
        ),
    ]
