# Generated by Django 3.2 on 2022-11-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_booking_goods_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='goods_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerwaybill',
            name='goods_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
