# Generated by Django 3.2 on 2022-11-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20221127_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, default=0.0, null=True)),
                ('vol_weight', models.FloatField(blank=True, default=0.0, null=True)),
                ('gross_weight', models.FloatField(blank=True, default=0.0, null=True)),
                ('chargable_weight', models.FloatField(blank=True, default=0.0, null=True)),
                ('length', models.FloatField(blank=True, default=0.0, null=True)),
                ('width', models.FloatField(blank=True, default=0.0, null=True)),
                ('height', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
    ]
