# Generated by Django 3.2 on 2022-11-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dimensions_booking_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensions',
            name='know_my_dimension',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
