# Generated by Django 3.2 on 2022-11-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_dimensions_know_my_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipper_comapny_name', to='core.companyprofile'),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
