# Generated by Django 3.2 on 2022-11-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20221128_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is_default'),
        ),
    ]
