# Generated by Django 3.2 on 2022-11-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_shipper_is_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='account_number',
            new_name='client_id',
        ),
    ]
