# Generated by Django 3.2 on 2023-02-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_account_number_companyprofile_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensions',
            name='current_session',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Current_Session#'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='piece_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
