# Generated by Django 3.2 on 2023-03-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230202_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='waybillno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Waybill No'),
        ),
    ]
