# Generated by Django 3.2 on 2023-04-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230329_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignee',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='consignee',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
