# Generated by Django 3.2 on 2023-04-18 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230402_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_number', models.CharField(blank=True, max_length=100, null=True)),
                ('waybillno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_waybill', to='core.booking')),
            ],
        ),
    ]
