# Generated by Django 3.2 on 2023-05-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230427_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenttype',
            name='infotrack_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
