# Generated by Django 3.2 on 2023-05-02 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_shipmenttype_infotrack_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status_id',
            field=models.IntegerField(blank=1, default=1, null=True),
        ),
    ]
