# Generated by Django 3.2 on 2023-05-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenttype',
            name='ClientID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipmenttype',
            name='ServiceType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipmenttype',
            name='ServiceTypeID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmenttype',
            name='shipment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
