# Generated by Django 3.2 on 2023-05-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20230504_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='customer_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
