# Generated by Django 3.2 on 2023-05-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_companyprofile_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='is_default',
            field=models.BooleanField(blank=True, default=1, null=True, verbose_name='is_default'),
        ),
    ]
